#!/bin/env python3

from car.car import Car

import yaml

with open('config.yaml', 'r') as f:
    conf = yaml.safe_load(f)


def main():

    car = Car()

    controller = None
    
    if conf['main']['controller-mode'] == 'ps':

        from car.controller.ps import PSController as Controller

        controller = Controller(device=conf['main']['device'], guest=car, connecting_using_ds4drv=False)

    else:
        print('Controller not found!')


    if controller:

        try:
            controller.listen()
        except (KeyboardInterrupt, SystemExit):
            controller.shutdown()


if __name__ == "__main__":
    main()
